# Generated by Django 6.0.2 on 2026-02-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'MUY BAJA'), (2, 'BAJA'), (3, 'MODERADA'), (4, 'ALTA'), (5, 'MUY ALTA')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(auto_created=True, choices=[(1, 'ENVIADO'), (2, 'EN REVISIÓN'), (3, 'CERRADO')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
